name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test_and_build:
    name: ${{ matrix.os }}_py${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python_version:
          ["3.9", "3.10", "3.11"]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: av2
          environment-file: conda/environment.yml
          mamba-version: "*"
          miniforge-version: latest
          python-version: ${{ matrix.python_version }}

      - name: Build `av2`.
        run: |
          maturin develop --extras test
          
      - name: Run `pytest`.
        run: |
          pytest tests --cov src/av2
